name: Docker Build CI

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: setup node
      uses: actions/setup-node@v1
      with:
        node-version: '14.18.0'
    - name: npm install
      run: npm install
    - name: npm lint
      run: npm run lint
    - name: npm build
      run: npm run bnw
    - name: npm tests
      run: npm run test:coverage
