# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: Publish CI

on:
  pull_request_target:
    branches: [ main ]
    types: [ closed ]

jobs:
  publish:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Install and speed Build
      run: |
        npm install
        npm run build:speed
    - name: versioning
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        npm run version:update
        npm run gen:log
    - name: Push new version
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
    - name: npm publish
      env:
        NPM_TOKEN: ${{secrets.NPM_TOKEN}}
      run: |
        npm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        npm publish
